### ISSUE TITLE
BPQChat: Spurious CHAT sent to chat

### ISSUE THREAD

**Issue by pe1rrr** [pe1rrr/bpq#11]
Upon login a user is sending the spurious word 'CHAT' and a carriage return into the chat lobby upon entering.

This bug has been around ages and its replicated by connecting to any of the BPQ chat servers using their full call sign and SSID via their local node. 

This affects all platforms.

Test:

C G8BPQ-9
C G8BPQ-4

Test:

C PE1RRR-7
C PE1RRR-4

Tested on NOTCHT (G8BPQ-4), RRRCHT, GYBCHT

These do not trigger the issue:

- Connection via the node and issuing CHAT command.
- Connection via ALIAS of Chat server.

If a user has the call sign set in their APPLICATION this would explain why their CHAT node command is triggering this issue.

**Comment by g8bpq** [comment]
This is caused by the "CMD_TO_APPL" flag being incorrectly set on chat streams. I've uploaded new versions of BPQChat.exe and LinBPQ that should fix it to my beta download area.

73,
John

**Comment by pe1rrr** [comment]
Splendid John, glad you could find that. Thanks man.

**Comment by pe1rrr** [comment]
> This is caused by the "CMD_TO_APPL" flag being incorrectly set on chat streams. I've uploaded new versions of BPQChat.exe and LinBPQ that should fix it to my beta download area.

>73,
>John
