### ISSUE TITLE
Webmail crash browser with unreadable characters

### ISSUE THREAD

**Issue by ClaudeMa** [pe1rrr/bpq#7]
the web interface frequently crashes filling the screen with unreadable characters.
Only closing the browser allows you to view the site again
Firefox, Chrome and Edge tested on Linux and Windows platform

BPQ Version 6.0.20.27 
Linux Debian 10 32bits

Source page content
`<meta http-equiv="refresh" content="0;url=/Node/NodeIndex.html"><html><head></head><body></body></html></body></html>`

![Capture](https://user-images.githubusercontent.com/2773730/96332994-9573c400-1067-11eb-9543-e6ea39dc9418.PNG)

**Comment by pe1rrr** [comment]
The latest beta is 6.0.20.50, can you update and see if that remedies the issue?

**Comment by pe1rrr** [comment]
```

#!/bin/bash
dir=/home/bpq/bpqbin
file="linbpq"
choice=$1

if [ "$choice" = "1" ] ; then
echo TEST
branch="Test"
else
echo BETA
branch="Beta"
fi


wget "http://www.cantab.net/users/john.wiseman/Downloads/${branch}/${file}" -O "
${dir}/${file}.new"
chmod 755 "${dir}/${file}.new"
chmod u+s "${dir}/${file}.new"
filedate=`date -r "${dir}/${file}.new" "+%Y%m%d_%H%M"`

mv "${dir}/${file}.new" "${dir}/${file}.${filedate}"

unlink "${dir}/${file}"
ln -s "${dir}/${file}.${filedate}" "${dir}/${file}"

echo "New: $filedate"

```

You may find this script useful to keep up to date with beta releases, adjust the path setting to fit your BPQ binary location. chmod 755 the script and place it in your ~/bin within you home directory.

**Comment by ClaudeMa** [comment]
Upgraded to 6.0.20.50

**Comment by pe1rrr** [comment]
Ok, thats good. This issue will be closed, if you experience the same or similar issue but on a different version, please report a new issue here. Thanks!
