### ISSUE TITLE
linbpq does not shut down at all when using signal SIGQUIT

### ISSUE THREAD

**Issue by n9seo** [pe1rrr/bpq#8]
Hi,

I was trying to write start/stop scripts and noticed that trying to use the following on linbpq does not actually cause the service to save its state and stop.

```bash
killall -SIGQUIT linbpq
```

As per say man page for signal  `man 7 signal` expected behavior is commonly when issued this signal that the process trigger a safe shutdown.  I did not check other signals.    A few other signals may be useful, probably SIGHUP which commonly is used in unix/linux to signal the app to reread its config file and apply it if possible.

**Comment by n9seo** [comment]
Hi,

Would be nice if I didnt forget this stuff but I had not had my morning coffee yet. :D

G8BPQ AX25 Packet Switch System Version 6.0.20.50 September 2020

OS:  Devuan GNU/Linux 3 (beowulf)

**Comment by pe1rrr** [comment]
The normal way to terminate linbpq is to use the SIGTERM signal to initiate a safe shutdown. I will leave this issue open and wait for a signal from John as to whether this is worth the time to implement.

**Comment by pe1rrr** [comment]
(today I learned)

```
SIGQUIT is the dump core signal. The terminal sends it to the foreground process when the user presses ctrl-\. The default behavior is to terminate the process and dump core, but it can be caught or ignored. The intention is to provide a mechanism for the user to abort the process. You can look at SIGINT as "user-initiated happy termination" and SIGQUIT as "user-initiated unhappy termination."

```

**Comment by pe1rrr** [comment]
```

SIGQUIT closes linbpq here, but does an an untidy close without closing connections or saving config. It should be closed with SIGTERM, which will close cleanly

73,
John
```

**Comment by pe1rrr** [comment]
I don't know what label to put on this I guess this is a wontfix? Can you confirm if you can shut down using the SIGTERM,  as your system will likely be all the better for it as using SIGQUIT in stop/start script in this context is not a good idea as it is unclean.

**Comment by n9seo** [comment]
Hi,

Ill close this.  I was mistaken and for some reason got it flipped around.
