### ISSUE TITLE
Webmail crash with unreadable characters

### ISSUE THREAD

**Issue by ClaudeMa** [pe1rrr/bpq#9]
Same as issue #7 after upgrade  to Linbpq 6.0.20.50 Debian 10 x86

after a long waiting delay I can display the contents source page

```
<!-- Version 6 8/11/2018 -->
<!DOCTYPE html> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"> 
<head> 
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/> 
<style type="text/css">
pre {margin-left: 4px;white-space: pre} 
#main{width:700px;position:absolute;left:0px;border:2px solid;background-color: #ffffff;}
</style>
<script src="/WebMail/webscript.js"></script>
<title>WebMail</title> 

</head>
<body onload="initialize(120)" onresize="initialize(120)">
<h3 align=center> F4IKH Webmail Interface - User F4IKH - Message List</h3>
<table align=center border=1 cellpadding=2 bgcolor=white><tr>

<td><a href=/WebMail/WMB?WF671652A>Bulls</a></td>
<td><a href=/WebMail/WMP?WF671652A>Personal</a></td>
<td><a href=/WebMail/WMT?WF671652A>NTS</a></td>
<td><a href=/WebMail/WMALL?WF671652A>All Types</a></td>
<td><a href=/WebMail/WMMine?WF671652A>Mine</a></td>
<td><a href="#" onclick="newmsg('WF671652A'); return false;">Send Message</a></td>
<td><a href=/WebMail/WMLogout?WF671652A>Logout</a></td>
<td><a href=/>Node Menu</a></td></tr></table>
<br>
<div align=left id="main" style="overflow:scroll;">
<pre align=left>     #  Date  XX   Len To      @       From    Subject

--- long list of messages ---

</pre>
</div> 


</body></html>

```

**Comment by pe1rrr** [comment]
I'd like to reproduce this here, unfortunately I haven't seen this happen yet- please can you describe:

- Any steps taken before this happens, or if it is random.
- Are you running any content blockers or 3rd party browser toolbars, if so which ones?
- 32bit kernel or 64bit?
- Is your linbpq the downloaded one or have you built from source?

Thanks for your update!

**Comment by ClaudeMa** [comment]
eally random sometimes just once or so at each change of pages

i have an addblockers -> i am going to disable it for the webmail url

i run 32 bits kernel 

my linbpq is downloaded from http://www.cantab.net/users/john.wiseman/Downloads/Beta/

**Comment by pe1rrr** [comment]
Claude, has the changes to the adblocker helped?

**Comment by ClaudeMa** [comment]
Hi red
No had more time to test yesterday.maybe today i can do some access to
webmail
73
Claude

Le mar. 20 oct. 2020 à 18:04, Red R. R. Tuby <notifications@github.com> a
écrit :

**Comment by ClaudeMa** [comment]
Not had time to do intensive tests but no crashes under normal use for 6 days
We can consider that the bug is fixed
